baseURL = 'https://kimix.com/'
languageCode = 'en-us'
title = 'Kimx Chemical Col.Ltd'
defaultContentLanguage = 'en'



# Languages  
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
mark = "EN"

[Languages.zh]
languageName = "中文"
languageCode = "zh-zh"
contentDir = "content/chinese"
weight = 2
mark = "中"


[taxonomies]
  category= "categories"
  scene = "scenes"