baseURL = 'https://roneo.itcouldbewor.se/'
languageCode = 'en-us'
defaultContentLanguage = 'en'


[params]
  title = 'Remix, a theme for Hugo fully editable with Netlify CMS'
  metaDescription = "Hugo + Netlify CMS + One click deploy to Netlify"


# Languages
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
mark = "EN"

[Languages.fr]
languageName = "fr"
languageCode = "fr-fr"
contentDir = "content/fr"
weight = 2
mark = "FR"


[taxonomies]
  category= "theme"
  scene = "scenes"
