# using git as backend store
backend:
  name: git-gateway
  branch: main
media_folder: "/static/media" # Folder where user uploaded files should go
public_folder: "/media"
editor:
  preview: false
locale: 'fr'

# Allow local visit
# You need to run at the root of the project `npx netlify-cms-proxy-server`
local_backend: true

# i18n https://www.netlifycms.org/docs/beta-features/#i18n-support
i18n:
  structure: multiple_folders
  locales: [ en, fr ]
  default_locale: en


# collections configuration
collections:
  - name: "sections"
    label: "Global settings"
    i18n:
      structure: single_file
      locales: [ en, fr ]
    files:
      - file: "data/home.yml"
        i18n: true
        label: "Home"
        name: "home"
        fields: [
          { label: "Title", name: "title", widget: string, i18n: true },
          { label: "Slogan", name: "slogan", widget: string, i18n: true },
          { label: "Description", name: "shortDescription", widget: "text", i18n: true },
          { label: "Header Image", name: "image", widget: "image" , media_folder: "/static/media" , public_folder: "/media", i18n: true },
          { label: "Register", name: "register", widget: string, i18n: true },
          { label: "Copyright", name: "copyright", widget: string, i18n: true },
        ]
      - file: "data/about.yml"
        label: "About"
        name: "about"
        i18n: true
        description: "Go to edit the about section"
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true },
            { label: "Items", name: "items", widget: "list", i18n: true, fields: [
              { label: "Icon", name: "icon", widget: string , i18n: true },
              { label: "Title", name: "title", widget: string, i18n: true },
              { label: "Content", name: "content", widget: text, i18n: true }]
            }
          ]
      - file: "data/products.yml"
        label: "Products"
        name: "productions"
        i18n: true
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true },
            { label: "PortText", name: "portText", widget: "text", i18n: true, required: false },
            { label: "Categories", name: "theme", widget: "list", i18n: true, fields: [
              { label: "Image", name: "coverImage", widget: "image" , media_folder: "/static/media" , public_folder: "/media", i18n: true },
              { label: "Name", name: "name", widget: string, i18n: true },
              { label: "theme", name: "cSlug", widget: select, i18n: true, options: [
                { label: "c1", value: "c1" },
                { label: "c2", value: "c2" },
                { label: "c3", value: "c3" },
                { label: "c4", value: "c4" },
                { label: "c5", value: "c5" },
              ] },
              { label: "Description", name: "description", widget: text , i18n: true },
            ] }
          ]
      - file: "data/scenes.yml"
        label: "Solutions"
        name: "industry"
        i18n: true
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true },
            { label: "PortText", name: "portText", widget: "text", i18n: true, required: false },
            { label: "scenes", name: "scenes", widget: "list", i18n: true, fields: [
              { label: "CoverImage", name: "coverImage", widget: "image" , media_folder: "/static/media" , public_folder: "/media", i18n: true },
              { label: "Name", name: "name", widget: string, i18n: true },
              { label: "Scene", name: "cSlug", widget: select, i18n: true, options: [
                { label: "化工", value: "s1" },
                { label: "食品", value: "s2" },
                { label: "石油", value: "s3" },
                { label: "制药", value: "s4" },
              ] },
              { label: "Description", name: "description", widget: text , i18n: true },
              { label: "icon", name: "icon", widget: string , i18n: true },
            ] }
          ]
      - file: "data/news.yml"
        label: "News"
        name: "news"
        i18n: true
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true },
            { label: "portText", name: "portText", widget: string, i18n: true, required: false },
          ]
      - file: "data/contact.yml"
        label: "Contact"
        name: "contact"
        i18n: true
        fields:
          [
            { label: "Title", name: "title", widget: string, i18n: true },
            { label: "BackgroundTitle", name: "backgroundTitle", widget: string, i18n: true },
            { label: "Subtitle", name: "subtitle", widget: string, i18n: true, required: false },
            { label: "Detail", name: "detail", widget: string, i18n: true },
            { label: "Location", name: "location", widget: string , i18n: true },
            { label: "Email", name: "email", widget: string , i18n: true, required: false },
            { label: "Fax", name: "fax", widget: string, i18n: true, required: false },
            { label: "Phone", name: "phone", widget: string , i18n: true, required: false },
            { label: "Languages", name: "languages", widget: string, i18n: true },
          ]
      - file: "data/glossary.yml"
        label: "Glossary"
        name: "glossary"
        i18n: true
        fields:
          [
            { label: "home", name: "home", widget: string, i18n: true },
            { label: "about", name: "about", widget: string, i18n: true },
            { label: "product", name: "product", widget: string, i18n: true },
            { label: "solution", name: "solution", widget: string, i18n: true },
            { label: "news", name: "news", widget: string, i18n: true },
            { label: "contact", name: "contact", widget: string, i18n: true },
            { label: "list", name: "list", widget: string, i18n: true },
          ]
  - name: "news"
    label: "Articles"
    folder: "content/english/news"
    path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: true
    fields:
      [
        { label: "Titre", name: "title", widget: "string" },
        # { label: "Publish Date", name: "date", widget: "datetime"},
        # { label: "Cover Image", name: "image", widget: "image" },
        # { label: "Summary", name: "summary", widget: "text" },
        { label: ".", name: "body", widget: "markdown" },
      ]
  - name: "news-fr"
    label: "News (fr)"
    folder: "content/fr/news"
    path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string" },
        { label: "Publish Date", name: "date", widget: "datetime", i18n: "duplicate" },
        { label: "Cover Image", name: "image", widget: "image" },
        { label: "Summary", name: "summary", widget: "text" },
        { label: "Body", name: "body", widget: "markdown" },
      ]
  - name: "products"
    label: "Products (English)"
    folder: "content/english/products"
    path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string"},
        { label: "Category", name: "theme", widget: "select", multiple: true, options:  [
          { label: "c1", value: "c1" },
          { label: "c2", value: "c2" },
          { label: "c3", value: "c3" },
          { label: "c4", value: "c4" },
          { label: "c5", value: "c5" },
        ]},
        { label: "Cover Image", name: "image", widget: "image" , media_folder: "/static/media" , public_folder: "/media" },
        { label: "Summary", name: "summary", widget: "text" },
        { label: "Body", name: "body", widget: "markdown" },
      ]
  - name: "products-fr"
    label: "Products (fr)"
    folder: "content/fr/products"
    path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string"},
        { label: "Category", name: "theme", widget: "select", multiple: true, options:  [
          { label: "c1", value: "c1" },
          { label: "c2", value: "c2" },
          { label: "c3", value: "c3" },
          { label: "c4", value: "c4" },
          { label: "c5", value: "c5" },
        ]},
        { label: "Cover Image", name: "image", widget: "image" , media_folder: "/static/media" , public_folder: "/media" },
        { label: "Summary", name: "summary", widget: "text" },
        { label: "Body", name: "body", widget: "markdown" },
      ]
  - name: "scene"
    label: "Scene (English)"
    folder: "content/english/scenes"
    path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string" },
        { label: "Scene", name: "scenes", widget: "select", multiple: true, options:  [
          { label: "化工", value: "s1" },
          { label: "食品", value: "s2" },
          { label: "石油", value: "s3" },
          { label: "制药", value: "s4" },
        ]},
        { label: "Cover Image", name: "image", widget: "image" , media_folder: "/static/media" , public_folder: "/media" },
        { label: "Summary", name: "summary", widget: "text" },
        { label: "Body", name: "body", widget: "markdown" },
      ]
  - name: "scene-fr"
    label: "Scene (fr)"
    folder: "content/fr/scenes"
    path: "{{slug}}"
    media_folder: "{{media_folder}}"
    public_folder: "{{public_folder}}"
    create: true
    fields:
      [
        { label: "Title", name: "title", widget: "string" },
        { label: "Scene", name: "scenes", widget: "select", multiple: true, options:  [
          { label: "化工", value: "s1" },
          { label: "食品", value: "s2" },
          { label: "石油", value: "s3" },
          { label: "制药", value: "s4" },
        ]},
        { label: "Cover Image", name: "image", widget: "image" , media_folder: "/static/media" , public_folder: "/media" },
        { label: "Summary", name: "summary", widget: "text" },
        { label: "Body", name: "body", widget: "markdown" },
      ]
